<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN_Comissioning" Id="{a47f7a2e-fd82-49d8-b01d-2a458ed98686}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_Comissioning
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[DALI_Commissioning();]]></ST>
    </Implementation>
    <LineIds Name="MAIN_Comissioning">
      <LineId Id="64" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>