# Dockerfile for an image which seeds the database
#

FROM --platform=$BUILDPLATFORM golang:1.25-alpine3.22 AS build_go

RUN apk add --no-cache git

WORKDIR /src

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY cmd ./cmd/
COPY internal ./internal/
COPY pkg ./pkg/

# set by the build engine
ARG TARGETARCH
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=$TARGETARCH
RUN --mount=type=cache,target=/go/pkg/mod \
    go build -o db-seeder ./cmd/tools/db-seeder


FROM alpine:3.22
LABEL vendor="Vanti Ltd"

COPY --from=build_go /src/db-seeder /app/
COPY ./example/config/vanti-ugs/app.conf.json /cfg/
RUN mkdir -p /data/secrets
RUN echo "" >> /data/secrets/postgres-password

ENTRYPOINT ["/app/db-seeder", "--look-back=744h", "--db-url=postgres://postgres@host.docker.internal:5432/smart_core", "--appconf=/cfg/app.conf.json"]
