# Dockerfile for sc-bos with the vanti ugs config
# This is based on the image built by the Dockerfile in the root of the repository.
# This dockerfile assumes it is being build using context from the root of the repository.

# Image built using the Dockerfile in the root of the repository
FROM localhost/vanti-dev-sc-bos:demo-ugs-base

# Files will be relative to the repository root
COPY example/config/vanti-ugs/ /cfg/
# Special system conf for the container env
COPY demo/vanti-ugs/system.conf.json /cfg/system.conf.json
EXPOSE 8443

ENTRYPOINT ["/app/sc-bos", "--policy-mode=check", "--appconf=/cfg/app.conf.json", "--sysconf=/cfg/system.conf.json", "--data=/data"]
