# Dockerfile for sc-bos
# This dockerfile performs the entire build itself.
# To enable fetching of private dependencies, an npmrc file must be be injected using a secret.
#
# To build, assuming your .npmrc is set up on your machine, run:
#     docker/podman build --secret=id=npmrc,src=$HOME/.npmrc .

FROM golang:1.23-alpine

COPY ./ui/conductor/dist /static
RUN mkdir /cfg
COPY ./demo/vanti-ugs/app.conf.json /cfg
COPY ./demo/vanti-ugs/system.conf.json /cfg
COPY ./demo/vanti-ugs/ui-config.json /cfg
COPY ./demo/vanti-ugs/assets /cfg/assets
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download -x

COPY cmd ./cmd/
COPY internal ./internal/
COPY pkg ./pkg/
RUN mkdir -p /data/secrets
RUN echo "" >> /data/secrets/postgres-password
RUN go build -o /app/sc-bos ./cmd/bos

EXPOSE 8443
EXPOSE 23557
EXPOSE 7000-7999

ENTRYPOINT ["/app/sc-bos", "--policy-mode=check", "--appconf=/cfg/app.conf.json", "--sysconf=/cfg/system.conf.json", "--data=/data"]
