/**
 * @fileoverview gRPC-Web generated client stub for smartcore.bos
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: emergency_light.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js')

var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.smartcore = {};
proto.smartcore.bos = require('./emergency_light_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.smartcore.bos.EmergencyLightApiClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.smartcore.bos.EmergencyLightApiPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smartcore.bos.StartEmergencyTestRequest,
 *   !proto.smartcore.bos.StartEmergencyTestResponse>}
 */
const methodDescriptor_EmergencyLightApi_StartFunctionTest = new grpc.web.MethodDescriptor(
  '/smartcore.bos.EmergencyLightApi/StartFunctionTest',
  grpc.web.MethodType.UNARY,
  proto.smartcore.bos.StartEmergencyTestRequest,
  proto.smartcore.bos.StartEmergencyTestResponse,
  /**
   * @param {!proto.smartcore.bos.StartEmergencyTestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smartcore.bos.StartEmergencyTestResponse.deserializeBinary
);


/**
 * @param {!proto.smartcore.bos.StartEmergencyTestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.smartcore.bos.StartEmergencyTestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.StartEmergencyTestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.EmergencyLightApiClient.prototype.startFunctionTest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/StartFunctionTest',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_StartFunctionTest,
      callback);
};


/**
 * @param {!proto.smartcore.bos.StartEmergencyTestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.smartcore.bos.StartEmergencyTestResponse>}
 *     Promise that resolves to the response
 */
proto.smartcore.bos.EmergencyLightApiPromiseClient.prototype.startFunctionTest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/StartFunctionTest',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_StartFunctionTest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smartcore.bos.StartEmergencyTestRequest,
 *   !proto.smartcore.bos.StartEmergencyTestResponse>}
 */
const methodDescriptor_EmergencyLightApi_StartDurationTest = new grpc.web.MethodDescriptor(
  '/smartcore.bos.EmergencyLightApi/StartDurationTest',
  grpc.web.MethodType.UNARY,
  proto.smartcore.bos.StartEmergencyTestRequest,
  proto.smartcore.bos.StartEmergencyTestResponse,
  /**
   * @param {!proto.smartcore.bos.StartEmergencyTestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smartcore.bos.StartEmergencyTestResponse.deserializeBinary
);


/**
 * @param {!proto.smartcore.bos.StartEmergencyTestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.smartcore.bos.StartEmergencyTestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.StartEmergencyTestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.EmergencyLightApiClient.prototype.startDurationTest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/StartDurationTest',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_StartDurationTest,
      callback);
};


/**
 * @param {!proto.smartcore.bos.StartEmergencyTestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.smartcore.bos.StartEmergencyTestResponse>}
 *     Promise that resolves to the response
 */
proto.smartcore.bos.EmergencyLightApiPromiseClient.prototype.startDurationTest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/StartDurationTest',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_StartDurationTest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smartcore.bos.StopEmergencyTestsRequest,
 *   !proto.smartcore.bos.StopEmergencyTestsResponse>}
 */
const methodDescriptor_EmergencyLightApi_StopEmergencyTest = new grpc.web.MethodDescriptor(
  '/smartcore.bos.EmergencyLightApi/StopEmergencyTest',
  grpc.web.MethodType.UNARY,
  proto.smartcore.bos.StopEmergencyTestsRequest,
  proto.smartcore.bos.StopEmergencyTestsResponse,
  /**
   * @param {!proto.smartcore.bos.StopEmergencyTestsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smartcore.bos.StopEmergencyTestsResponse.deserializeBinary
);


/**
 * @param {!proto.smartcore.bos.StopEmergencyTestsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.smartcore.bos.StopEmergencyTestsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.StopEmergencyTestsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.EmergencyLightApiClient.prototype.stopEmergencyTest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/StopEmergencyTest',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_StopEmergencyTest,
      callback);
};


/**
 * @param {!proto.smartcore.bos.StopEmergencyTestsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.smartcore.bos.StopEmergencyTestsResponse>}
 *     Promise that resolves to the response
 */
proto.smartcore.bos.EmergencyLightApiPromiseClient.prototype.stopEmergencyTest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/StopEmergencyTest',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_StopEmergencyTest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smartcore.bos.GetTestResultSetRequest,
 *   !proto.smartcore.bos.TestResultSet>}
 */
const methodDescriptor_EmergencyLightApi_GetTestResultSet = new grpc.web.MethodDescriptor(
  '/smartcore.bos.EmergencyLightApi/GetTestResultSet',
  grpc.web.MethodType.UNARY,
  proto.smartcore.bos.GetTestResultSetRequest,
  proto.smartcore.bos.TestResultSet,
  /**
   * @param {!proto.smartcore.bos.GetTestResultSetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smartcore.bos.TestResultSet.deserializeBinary
);


/**
 * @param {!proto.smartcore.bos.GetTestResultSetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.smartcore.bos.TestResultSet)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.TestResultSet>|undefined}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.EmergencyLightApiClient.prototype.getTestResultSet =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/GetTestResultSet',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_GetTestResultSet,
      callback);
};


/**
 * @param {!proto.smartcore.bos.GetTestResultSetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.smartcore.bos.TestResultSet>}
 *     Promise that resolves to the response
 */
proto.smartcore.bos.EmergencyLightApiPromiseClient.prototype.getTestResultSet =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/GetTestResultSet',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_GetTestResultSet);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.smartcore.bos.PullTestResultRequest,
 *   !proto.smartcore.bos.PullTestResultsResponse>}
 */
const methodDescriptor_EmergencyLightApi_PullTestResultSets = new grpc.web.MethodDescriptor(
  '/smartcore.bos.EmergencyLightApi/PullTestResultSets',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.smartcore.bos.PullTestResultRequest,
  proto.smartcore.bos.PullTestResultsResponse,
  /**
   * @param {!proto.smartcore.bos.PullTestResultRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.smartcore.bos.PullTestResultsResponse.deserializeBinary
);


/**
 * @param {!proto.smartcore.bos.PullTestResultRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.PullTestResultsResponse>}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.EmergencyLightApiClient.prototype.pullTestResultSets =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/PullTestResultSets',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_PullTestResultSets);
};


/**
 * @param {!proto.smartcore.bos.PullTestResultRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.smartcore.bos.PullTestResultsResponse>}
 *     The XHR Node Readable Stream
 */
proto.smartcore.bos.EmergencyLightApiPromiseClient.prototype.pullTestResultSets =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/smartcore.bos.EmergencyLightApi/PullTestResultSets',
      request,
      metadata || {},
      methodDescriptor_EmergencyLightApi_PullTestResultSets);
};


module.exports = proto.smartcore.bos;

