name: Create and publish Docker image

on:
  push:
    tags:
     - 'v*'

  workflow_dispatch:
    inputs:
      override_tag:
        description: 'Force Docker image tag to use'
        required: false
        type: string
        default: ''

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      actions: read
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Docker registry as GitHub Actions
      - name: Log in to the Container registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extracts metadata from Git to add to the Docker image
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # creates docker images tagged like:
          #  - edge         (when on main branch)
          #  - sha-abcdef1  (with Git short SHA)
          # for tag push to v2025.1.2, creates docker images tagged like:
          #  - 2025.1
          #  - 2025.1.2
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=edge,branch=main

      - name: Build and push Docker image (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          # only push if not running locally using act
          push: ${{ !env.ACT }}
          tags: ${{ inputs.override_tag || steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
