name: Go Test

on:
  push:
    branches: [ main, tools/code-coverage ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/smart-core-os/*,github.com/vanti-dev/*
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version: '^1.24.x'
      - name: Private repo auth
        run: |
          git config --global url."https://${{ secrets.GO_MOD_TOKEN }}:x-oauth-basic@github.com/smart-core-os".insteadOf "https://github.com/smart-core-os"
          git config --global url."https://${{ secrets.GO_MOD_TOKEN }}:x-oauth-basic@github.com/vanti-dev".insteadOf "https://github.com/vanti-dev"

      - name: Test all with coverage
        uses: robherley/go-test-action@v0
        with:
          testArguments: ./pkg/... ./internal/...